apiVersion: v1
kind: Service
metadata:
  name: traefik-api
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-kube-system
  ports:
  - port: 9000
    name: traefik
    targetPort: 9000
    protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-auth-middleware
  namespace: kube-system
spec:
  basicAuth:
    secret: traefik-auth
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-dashboard
  namespace: kube-system
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-traefik-auth-middleware@kubernetescrd
spec:
  rules:
  - host: hahafhaharpi4.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik-api
            port:
              name: traefik