apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-auth-middleware
  namespace: kube-system
spec:
  basicAuth:
    secret: traefik-auth
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: kube-system
spec:
  entryPoints:
    - web
    - traefik
  routes:
    - kind: Rule
      match: Host(`hahafhaharpi4.local`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      middlewares:
        - name: traefik-auth-middleware
      services:
        - kind: TraefikService
          name: api@internal
